version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: telemetrydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d telemetrydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./TelemetryApi
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=telemetrydb;Username=demo;Password=demo
    ports:
      - "5000:80"
    restart: on-failure

volumes:
  pgdata:
