FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["TelemetryApi.csproj", "."]
RUN dotnet restore "./TelemetryApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./TelemetryApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

# publish stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TelemetryApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# production stage
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TelemetryApi.dll"]
